u = load('post_outputu.txt');
v = load('post_outputv.txt');
xlength = 1.0;
ylength = 1.0;
imax = 128;
jmax = 128;
dx = xlength/(imax);
dy = ylength/(jmax);
X=0:dx:xlength;
Y=0:dy:ylength;
[xx,yy]=meshgrid(X,Y);
axis([0,1.1,0,2.5]);
quiver(xx,yy,u,v,5);
axis([0,1.1,0,2.5]);
fig = figure;
streamslice(xx,yy,u,v);
axis tight;
print(fig,'MySavedPlot','-dpng');
quit;
